/*
 Navicat MySQL Data Transfer

 Source Server         : _localhost
 Source Server Type    : MariaDB
 Source Server Version : 100428 (10.4.28-MariaDB)
 Source Host           : localhost:3306
 Source Schema         : tw_world

 Target Server Type    : MariaDB
 Target Server Version : 100428 (10.4.28-MariaDB)
 File Encoding         : 65001

 Date: 11/01/2024 13:18:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for pool_template
-- ----------------------------
DROP TABLE IF EXISTS `pool_template`;
CREATE TABLE `pool_template`  (
  `entry` mediumint(8) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Pool entry',
  `max_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Max number of objects (0) is no limit',
  `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `flags` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `instance` mediumint(9) NOT NULL DEFAULT 0,
  PRIMARY KEY (`entry`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of pool_template
-- ----------------------------
INSERT INTO `pool_template` VALUES (1, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (2, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (3, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (4, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (5, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (6, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (7, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (8, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (9, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (10, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (11, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (12, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (13, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (14, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (15, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (16, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (17, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (18, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (19, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (20, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (21, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (22, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (23, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (24, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (25, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (26, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (27, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (28, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (29, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (30, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (31, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (32, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (33, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (34, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (35, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (36, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (37, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (38, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (39, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (40, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (41, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (42, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (43, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (44, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (45, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (46, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (47, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (48, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (49, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (50, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (51, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (52, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (53, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (54, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (55, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (56, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (57, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (58, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (59, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (60, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (61, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (62, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (63, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (64, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (65, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (66, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (67, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (68, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (69, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (70, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (71, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (72, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (73, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (74, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (75, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (76, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (77, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (78, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (79, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (80, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (81, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (82, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (83, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (84, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (85, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (86, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (87, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (88, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (89, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (90, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (91, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (92, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (93, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (94, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (95, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (96, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (97, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (98, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (99, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (100, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (101, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (102, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (103, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (145, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (146, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (147, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (148, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (149, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (153, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (154, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (155, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (156, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (157, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (158, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (159, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (160, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (161, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (163, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (164, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (165, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (166, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (167, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (168, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (169, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (170, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (171, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (172, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (173, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (174, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (175, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (176, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (177, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (178, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (179, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (180, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (181, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (182, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (183, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (184, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (185, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (186, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (187, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (188, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (189, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (190, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (191, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (192, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (193, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (194, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (195, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (196, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (197, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (198, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (199, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (200, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (201, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (202, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (203, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (204, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (205, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (206, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (207, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (208, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (209, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (210, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (211, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (212, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (213, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (214, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (215, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (216, 1, 'Floating Wreckage', 0, 0);
INSERT INTO `pool_template` VALUES (217, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (218, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (219, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (220, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (221, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (222, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (223, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (224, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (225, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (226, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (227, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (228, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (229, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (230, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (231, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (232, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (233, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (234, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (235, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (236, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (237, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (238, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (239, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (240, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (241, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (242, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (243, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (244, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (245, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (246, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (247, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (248, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (249, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (250, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (251, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (252, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (253, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (254, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (255, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (256, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (257, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (258, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (259, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (260, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (261, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (262, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (263, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (264, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (265, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (266, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (267, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (268, 1, 'Floating Wreckage', 0, 0);
INSERT INTO `pool_template` VALUES (269, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (270, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (271, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (330, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (331, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (333, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (334, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (1126, 16, 'Bruiseweed in Redridge 98 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1306, 8, 'Mageroyals in Redridge 24 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (22905, 1, 'Spawn Elite Rare LBRS : Spirestone Butcher', 0, 0);
INSERT INTO `pool_template` VALUES (22906, 1, 'Spawn Elite Rare LBRS : Spirestone Battle Lord', 0, 0);
INSERT INTO `pool_template` VALUES (22903, 1, 'Spawn Elite Rare LBRS : Ghok Bashguud', 0, 0);
INSERT INTO `pool_template` VALUES (22904, 1, 'Spawn Elite Rare LBRS : Crystal Fang', 0, 0);
INSERT INTO `pool_template` VALUES (32901, 1, 'Spawn Elite Rare Strat Eca : Skul', 0, 0);
INSERT INTO `pool_template` VALUES (22901, 1, 'Spawn Elite Rare UBRS : Jed', 0, 0);
INSERT INTO `pool_template` VALUES (42901, 1, 'Spawn Elite Rare HT Ouest : Tsu zee', 0, 0);
INSERT INTO `pool_template` VALUES (23002, 1, 'Spawn Elite Rare BRD : Panzor the Invincible', 0, 0);
INSERT INTO `pool_template` VALUES (42905, 2, 'Patch of Elemental Water Kalimdor', 0, 0);
INSERT INTO `pool_template` VALUES (22907, 1, 'Spawn Elite Rare LBRS : Spirestone Lord Magus', 0, 0);
INSERT INTO `pool_template` VALUES (1125, 8, 'Peaceblooms in Redridge 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1124, 12, 'Earthroots in Redridge 24 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1121, 5, 'Gold Veins in Duskwood 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1120, 7, 'Tin Veins in Duskwood 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1119, 10, 'Copper Veins in Duskwood 30 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1118, 5, 'Iron Deposits in Duskwood 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1117, 6, 'Kingsblood in Duskwood 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1115, 14, 'Bruiseweed in Duskwood 85 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1116, 5, 'Mageroyals in Duskwood 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1114, 3, 'Wildsteel Blooms in Duskwood 10 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1122, 6, 'Stranglekelp in Westfall 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1113, 20, 'Briarthorn in Duskwood 98 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1112, 9, 'Tin Veins in Westfall 61 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1111, 8, 'Copper Veins in Westfall 57 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1110, 13, 'Bruiseweed in Westfall 76 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1108, 15, 'Mageroyals in Westfall 45 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1109, 12, 'Briarthorn in Westfall 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1107, 15, 'Peaceblooms in Westfall 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1106, 19, 'Silverleafs in Westfall 23 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1105, 12, 'Earthroots in Westfall 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1101, 12, 'Bruiseweed in Darkshore 39 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1100, 8, 'Briarthorn in Darkshore 50 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1099, 6, 'Tin Veins in Darkshore 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1098, 28, 'Copper Veins in Darkshore 84 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1097, 20, 'Mageroyals in Darkshore 61 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1094, 12, 'Earthroots in Darkshore 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1096, 12, 'Peaceblooms in Darkshore 18 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1095, 18, 'Silverleafs in Darkshore 64 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1167, 6, 'Tin Veins in Loch Modan 18 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1166, 27, 'Copper Veins in Loch Modan 82 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1164, 12, 'Bruiseweed in Loch Modan 61 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1165, 5, 'Briarthorn in Loch Modan 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1163, 6, 'Mageroyals in Loch Modan 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1162, 20, 'Silverleafs in Loch Modan 77 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1161, 19, 'Peaceblooms in Loch Modan 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1160, 9, 'Earthroots in Loch Modan 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1157, 17, 'Tin Veins in Wetlands 52 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1158, 6, 'Iron Deposits in Wetlands 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1159, 7, 'Silver Veins in Wetlands 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1154, 5, 'Mageroyals in Wetlands 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1155, 8, 'Kingsblood in Wetlands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1156, 11, 'Copper Veins in Wetlands 35 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1153, 12, 'Liferoots in Wetlands 51 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1152, 12, 'Wild Steelblooms in Wetlands 47 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1149, 10, 'Stranglekelp in Wetlands 41 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1150, 16, 'Bruiseweed in Wetlands 97 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1151, 9, 'Briarthorn in Wetlands 27 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1148, 5, 'Grave Moss in Wetlands 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1199, 5, 'Purple Lotus in Stranglethorn 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1179, 15, 'Liferoots in Stranglethorn 52 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1178, 4, 'Truesilver Veins in Stranglethorn 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1177, 8, 'Mithril Deposits in Stranglethorn 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1176, 13, 'Gold Veins in Stranglethorn 51 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1174, 30, 'Goldthorn in Stranglethorn 184 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1175, 14, 'Iron Deposits in Stranglethorn 44 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1173, 25, 'Khadgars Whisker in Stranglethorn 179 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1172, 11, 'Fadeleaf in Stranglethorn 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1171, 19, 'Stranglekelp in Stranglethorn 57 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1170, 17, 'Kingsblood in Stranglethorn 53 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1169, 13, 'Wild Steelblooms in Stranglethorn 41 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1198, 6, 'Ooze Covered Mithril in Feralas 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1197, 2, 'Truesilver Deposits in Feralas 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1196, 10, 'Iron Deposits in Feralas 30 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1195, 6, 'Mithril Deposits in Feralas 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1193, 6, 'Liferoots in Feralas 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1194, 5, 'Golden Sansam in Feralas 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1192, 6, 'Sungrass in Feralas 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1189, 4, 'Khadgars Whisker in Feralas 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1190, 9, 'Stranglekelp in Feralas 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1191, 8, 'Goldthorn in Feralas 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1257, 3, 'Small Thorium Veins in Hinterlands 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1255, 10, 'Mithril Deposits in Hinterlands 24 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1256, 6, 'Truesilver Deposits in Hinterlands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1254, 9, 'Purple Lotus in Hinterlands 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1253, 8, 'Golden Sansam in Hinterlands 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1252, 9, 'Fadeleafs in Hinterlands 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1250, 15, 'Sungrass in Hinterlands 77 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1251, 5, 'Liferoots in Hinterlands 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1249, 16, 'Goldthron in Hinterlands 50 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1248, 9, 'Khadgars Whisker in Hinterlands 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1247, 8, 'Ghost Mushrooms in Hinterlands 30 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1271, 6, 'Mithril Deposits in Western Plaguelands 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1263, 8, 'Small Thorium Veins in Western Plaguelands 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1262, 4, 'Truesilver Deposits in Western Plaguelands 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1261, 3, 'Sungrass in Western Plaguelands 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1260, 6, 'Dreamfoil in Western Plaguelands 33 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1259, 12, 'Arthas Tears in Western Plaguelands 46 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1258, 12, 'Plagueblooms in Western Plaguelands 74 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1235, 13, 'Rich Thorium Veins in Winterspring 41 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1273, 4, 'Small Thorium Veins in Eastern Plaguelands 13 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1272, 5, 'Truesilver Deposits in Eastern Plaguelands 23 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (303, 1, 'Black Lotus spawns - Burning Steppes', 0, 0);
INSERT INTO `pool_template` VALUES (1269, 3, 'Mountain Silversage in Eastern Plaguelands 11 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1268, 8, 'Golden Sansam in Eastern Plaguelands 45 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1267, 12, 'Dreamfoil in Eastern Plaguelands 71 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1266, 20, 'Arthas Tears in Eastern Plaguelands 144 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1279, 16, 'Mithril Deposits in Blasted Lands 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1280, 10, 'Small Thorium Veins in Blasted Lands 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1265, 30, 'Plagueblooms in Eastern Plaguelands 144 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1278, 6, 'Truesilver Deposits in Blasted Lands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1276, 12, 'Fireblooms in Blasted Lands 44 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1277, 8, 'Sungrass in Blasted Lands 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1275, 8, 'Gromsblood in Blasted Lands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1295, 4, 'Small Thorium Veins in Searing Gorge 13 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1294, 10, 'Truesilver Deposits in Searing Gorge 39 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1293, 10, 'Mithril Deposits in Searing Gorge 21 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1292, 2, 'Iron Deposits in Searing Gorge 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1291, 10, 'Fireblooms in Searing Gorge 49 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1224, 8, 'Golden Sansam in Silithus 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (302, 1, 'Black Lotus spawns - Winterspring', 0, 0);
INSERT INTO `pool_template` VALUES (1222, 2, 'Mountain Silversage in Silithus 6 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1220, 14, 'Small Thorium Veins in Silithus 42 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1221, 4, 'Dreamfoil in Silithus 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1232, 8, 'Small Thorium Veins in Felwood 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1219, 2, 'Truesilver Deposits in Silithus 6 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1231, 5, 'Truesilver Deposits in Felwood 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1230, 10, 'Golden Sansam in Felwood 30 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1229, 5, 'Sungrass in Felwood 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1228, 9, 'Dreamfoil in Felwood 54 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1227, 11, 'Plagueblooms in Felwood 63 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1226, 7, 'Arthas Tears in Felwood 23 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1225, 12, 'Gromsblood in Felwood 56 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1236, 26, 'Icecaps in Winterspring 153 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (301, 1, 'Black Lotus spawns - Eastern Plaguelands', 0, 0);
INSERT INTO `pool_template` VALUES (1237, 14, 'Mountain Silversage in Winterspring 85 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1217, 8, 'Rich Thorium Veins in Ungoro 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1234, 2, 'Truesilver Deposits in Winterspring 11 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1246, 11, 'Rich Thorium Veins in Azshara 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1233, 7, 'Small Thorium Veins in Winterspring 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1245, 3, 'Small Thorium Veins in Azshara 10 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1243, 9, 'Mountain Silversage in Azshara 52 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1244, 3, 'Truesilver Deposits in Azshara 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1242, 20, 'Dreamfoil in Azshara 122 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1241, 15, 'Golden Sansam in Azshara 87 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1239, 20, 'Purple Lotus in Azshara 114 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1240, 20, 'Sungrass in Azshara 93 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1188, 22, 'Mithril Deposits in Arathi 48 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1184, 10, 'Liferoots in Arathi 47 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1185, 21, 'Wild Steelblooms in Arathi 127 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1186, 60, 'Iron Deposits in Arathi 182 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1183, 15, 'Fadeleafs in Arathi 55 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1182, 15, 'Khadgars Whisker in Arathi 71 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1181, 20, 'Goldthorn in Arathi 120 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1187, 5, 'Tin Veins in Arathi 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1071, 11, 'Fadeleafs in Alterac 33 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1180, 8, 'Kingsblood in Arathi 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1069, 16, 'Mithril Deposits in Alterac 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1063, 8, 'Liferoots in Alterac 36 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1068, 26, 'Iron Deposits in Alterac 78 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1062, 9, 'Wintersbite in Alterac 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1061, 5, 'Wild Steelblooms in Alterac 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1060, 2, 'Grave Moss in Alterac 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1058, 12, 'Goldthorn in Alterac 81 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1059, 8, 'Khadgars Whisker in Alterac 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1057, 2, 'Kingsblood in Alterac 6 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1056, 8, 'Bruiseweed in Alterac 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1123, 8, 'Stranglekelp in Hillsbrad 24 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1070, 11, 'Iron Deposits in Hillsbrad 33 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1066, 6, 'Copper Veins in Hillsbrad 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1067, 9, 'Tin Veins in Hillsbrad 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1051, 12, 'Kingsblood in Hillsbrad 38 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1050, 9, 'Briarthorn in Hillsbrad 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1049, 4, 'Mageroyals in Hillsbrad 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1048, 17, 'Bruiseweed in Hillsbrad 102 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1065, 5, 'Stranglekelp in Silverpine Forest 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1047, 13, 'Bruiseweed in Silverpine Forest 76 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1046, 9, 'Briarthorn in Silverpine Forest 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1045, 15, 'Tin Veins in Silverpine Forest 21 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1044, 30, 'Copper Veins in Silverpine Forest 92 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1043, 10, 'Mageroyals in Silverpine Forest 32 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1041, 11, 'Peaceblooms in Silverpine Forest 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1042, 18, 'Silverleafs in Silverpine Forest 55 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1040, 10, 'Earthroots in Silverpine Forest 13 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1104, 3, 'Liferoots in Dustwallow Marsh 10 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1103, 3, 'Goldthorn in Dustwallow Marsh 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1039, 2, 'Kingsblood in Dustwallow Marsh 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1102, 3, 'Khadgars Whisker in Dustwallow Marsh 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1083, 2, 'Gravemoss in Barrens 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1064, 15, 'Stranglekelp in Barrens 52 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1168, 9, 'Wild Steelblooms in Barrens 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1038, 11, 'Kingsblood in Barrens 33 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1037, 22, 'Briarthorn in Barrens 77 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1036, 16, 'Bruiseweed in Barrens 95 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1035, 2, 'Silver Veins in Barrens 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1034, 18, 'Tin Veins in Barrens 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1033, 40, 'Copper Veins in Barrens 147 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1032, 30, 'Mageroyals in Barrens 227 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1030, 28, 'Peaceblooms in Barrens 86 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1031, 25, 'Silverleafs in Barrens 100 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1029, 21, 'Earthroots in Barrens 127 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1136, 5, 'Kingsblood in Thousand Needles 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1135, 9, 'Gold Veins in Thousand Needles 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1134, 10, 'Wild Steelblooms in Thousand Needles 42 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1133, 12, 'Bruiseweed in Thousand Needles 59 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1132, 34, 'Iron Deposits in Thousand Needles 102 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1131, 5, 'Tin Veins in Thousand Needles 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1130, 16, 'Copper Veins in Thousand Needles 48 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1028, 21, 'Copper Veins in Mulgore 64 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1027, 25, 'Silverleafs in Mulgore 73 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1026, 25, 'Peaceblooms in Mulgore 56 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1025, 15, 'Earthroots in Mulgore 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1024, 30, 'Copper Veins in Durotar 127 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1023, 4, 'Mageroyals in Durotar 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1022, 25, 'Silverleafs in Durotar 137 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1021, 15, 'Earthroots in Durotar 33 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1020, 25, 'Peaceblooms in Durotar 53 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1218, 12, 'Mountain Silversage in Ungoro 70 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1299, 14, 'Rich Thorium Veins in Burning Steppes 44 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1296, 6, 'Mithril Deposits in Burning Steppes 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1297, 5, 'Truesilver Deposits in Burning Steppes 138 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1298, 13, 'Small Thorium Veins in Burning Steppes 40 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1274, 6, 'Rich Thorium Veins in Eastern Plaguelands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1300, 10, 'Golden Sansam in Burning Steppes 32 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1301, 19, 'Dream Foil in Burning Steppes 57 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1302, 9, 'Mountain Silversage in Burning Steppes 29 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1303, 6, 'Sungrass in Burning Steppes 20 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (300, 1, 'Black Lotus spawns - Silithus', 0, 0);
INSERT INTO `pool_template` VALUES (1289, 14, 'Mithril Deposits in Badlands 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1290, 7, 'Truesilver Deposits in Badlands 27 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1281, 7, 'Fireblooms in Badlands 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1282, 8, 'Khadgars Whisker in Badlands 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1283, 13, 'Goldthorn in Badlands 41 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1284, 7, 'Kingsblood in Badlands 21 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1285, 9, 'Fadeleafs in Badlands 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1286, 2, 'Purple Lotus in Badlands 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1287, 27, 'Iron Deposits in Badlands 83 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1288, 8, 'Gold Veins in Badlands 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1072, 23, 'Bruiseweed in Ashenvale 137 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1073, 20, 'Briarthorn in Ashenvale 62 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1074, 10, 'Tin Veins in Ashenvale 30 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1075, 23, 'Copper Veins in Ashenvale 69 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1076, 18, 'Stranglekelp in Ashenvale 107 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1077, 21, 'Mageroyals in Ashenvale 63 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1078, 9, 'Kingsblood in Ashenvale 27 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1079, 19, 'Iron Deposits in Ashenvale 58 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1080, 11, 'Silver Veins in Ashenvale 58 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1081, 10, 'Wild Steelblooms in Ashenvale 57 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1305, 4, 'Purple Lotus in Ashenvale 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1137, 14, 'Bruiseweed in Desolace 50 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1138, 4, 'Kingsblood in Desolace 13 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1139, 2, 'Copper Veins in Desolace 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1140, 5, 'Tin Veins in Desolace 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1141, 28, 'Iron Deposits in Desolace 86 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1142, 3, 'Wild Steelblooms in Desolace 10 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1143, 6, 'Gromsblood in Desolace 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1145, 8, 'Stranglekelp in Desolace 24 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1144, 3, 'Liferoots in Desolace 11 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1146, 16, 'Mithril Deposits in Desolace 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1147, 2, 'Truesilver Deposits in Desolace 11 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1082, 9, 'Various Herbs in Stonetalon (and Barrens) 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1086, 22, 'Bruiseweed in Stonetalon 169 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1085, 15, 'Wild Steelblooms in Stonetalon 92 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1087, 10, 'Briarthorn in Stonetalon 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1088, 8, 'Kingsblood in Stonetalon 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1089, 26, 'Copper Veins in Stonetalon 79 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1090, 15, 'Tin Veins in Stonetalon 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1091, 7, 'Iron Deposits in Stonetalon 23 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1092, 8, 'Silver Veins in Stonetalon 11 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1093, 5, 'Gold Veins in Stonetalon 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1200, 15, 'Iron Deposits in Tanaris 47 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1201, 15, 'Gold Veins in Tanaris 60 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1202, 6, 'Truesilver Deposits in Tanaris 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1203, 16, 'Mithril Deposits in Tanaris 37 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1204, 23, 'Small Thorium Veins in Tanaris 70 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1205, 10, 'Purple Lotus in Tanaris 32 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1206, 4, 'Golden Sansam in Tanaris 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1207, 2, 'Dreamfoil in Tanaris 13 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1208, 15, 'Fireblooms in Tanaris 62 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1210, 3, 'Truesilver Deposits in Ungoro 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1211, 13, 'Small Thorium Veins in Ungoro 39 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1212, 14, 'Dreamfoil in Ungoro 83 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1213, 3, 'Truesilver Veins in Ungoro 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1214, 16, 'Golden Sansam in Ungoro 94 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1215, 7, 'Sungrass in Ungoro 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1216, 5, 'Blindweed in Ungoro 16 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1127, 9, 'Briarthorn in Redridge 28 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1128, 17, 'Copper Veins in Redridge 52 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1129, 12, 'Tin Veins in Redridge 36 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1001, 13, 'Earthroots in Teldrassil 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1002, 25, 'Peaceblooms in Teldrassil 42 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1003, 25, 'Silverleafs in Teldrassil 44 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1004, 4, 'Mageroyals in Teldrassil 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1005, 15, 'Earthroots in Tirisfal 32 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1006, 25, 'Peaceblooms in Tirisfal 51 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1007, 25, 'Silverleafs in Tirisfal 69 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1008, 15, 'Copper Veins in Tirisfal 45 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1009, 22, 'Gloom Weed in Tirisfal 67 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1010, 9, 'Doom Weed in Tirisfal 27 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1011, 15, 'Earthroots in Elwynn Forest 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1012, 25, 'Peaceblooms in Elwynn Forest 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1013, 25, 'Silverleafs in Elwynn Forest 59 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1015, 28, 'Copper Veins in Elwynn Forest 86 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1016, 15, 'Earthroots in Dun Morogh 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1017, 25, 'Peaceblooms in Dun Morogh 41 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1018, 25, 'Silverleafs in Dun Morogh 54 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1019, 25, 'Copper Veins in Dun Morogh 76 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1307, 10, 'Blindweed in Swamp of Sorrows (1) 61 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1308, 11, 'Goldthorn in Swamp of Sorrows (1) 34 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1309, 8, 'Khadgars Whisker in Swamp of Sorrows (1) 26 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1317, 2, 'Liferoots in Swamp of Sorrows (1) 6 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1318, 4, 'Iron Deposits in Swamp of Sorrows (1) 14 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1315, 6, 'Mithril Deposits in Swamp of Sorrows (2) 17 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1316, 2, 'Truesilver Deposits in Swamp of Sorrows (2) 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1310, 8, 'Khadgars Whisker in Swamp of Sorrows (2) 25 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1311, 13, 'Fadeleafs in Swamp of Sorrows (2) 50 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1312, 11, 'Blindweed in Swamp of Sorrows (2) 64 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1313, 15, 'Goldthorn in Swamp of Sorrows (2) 56 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1314, 10, 'Iron Deposits in Swamp of Sorrows (2) 31 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (22908, 1, 'GO Bijou\'s Belongings 5 spawn possible', 0, 0);
INSERT INTO `pool_template` VALUES (12903, 1, 'Tel\'abim Black Lotus', 0, 0);
INSERT INTO `pool_template` VALUES (1264, 2, 'Rich Thorium Veins in Western Plaguelands', 0, 0);
INSERT INTO `pool_template` VALUES (10001, 1, 'Spawn Elite Prison : Bruegal Ironknuckle', 0, 0);
INSERT INTO `pool_template` VALUES (32910, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32911, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32912, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32913, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32914, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32915, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32916, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32917, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32918, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32919, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32920, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32921, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32922, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32923, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32924, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32925, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32926, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32927, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32928, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32929, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32930, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32931, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32932, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32933, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32934, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32935, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32936, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32937, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32938, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32939, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32940, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32941, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32942, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32943, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32944, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32945, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32946, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32947, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32948, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32949, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32950, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32951, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32952, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32953, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32954, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32955, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32956, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32957, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32958, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32959, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32961, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32962, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32963, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32964, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32966, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32967, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32968, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (1502, 1, 'Zul\'Farrak : Sandarr Dunereaver', 0, 0);
INSERT INTO `pool_template` VALUES (32970, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32971, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (32972, 1, 'Strat : Supply Crate', 0, 0);
INSERT INTO `pool_template` VALUES (10003, 4, 'Dust Devil', 0, 0);
INSERT INTO `pool_template` VALUES (1600, 1, 'Dire Maul Dusty Tomes, 11 total', 0, 0);
INSERT INTO `pool_template` VALUES (3001, 1, 'Cat Figurine 1', 0, 0);
INSERT INTO `pool_template` VALUES (3002, 1, 'Cat Figurine 2', 0, 0);
INSERT INTO `pool_template` VALUES (3003, 1, 'Cat Figurine 3', 0, 0);
INSERT INTO `pool_template` VALUES (3004, 1, 'Cat Figurine 4', 0, 0);
INSERT INTO `pool_template` VALUES (3005, 1, 'Cat Figurine 5', 0, 0);
INSERT INTO `pool_template` VALUES (3006, 1, 'Cat Figurine 6', 0, 0);
INSERT INTO `pool_template` VALUES (3007, 1, 'Cat Figurine 7', 0, 0);
INSERT INTO `pool_template` VALUES (3008, 1, 'Cat Figurine 8', 0, 0);
INSERT INTO `pool_template` VALUES (3009, 1, 'Cat Figurine 9', 0, 0);
INSERT INTO `pool_template` VALUES (3010, 1, 'Cat Figurine 10', 0, 0);
INSERT INTO `pool_template` VALUES (2000, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2001, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2002, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2003, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2004, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2005, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2006, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2007, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2008, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2009, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2010, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2011, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2012, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2013, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2014, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2015, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2016, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2017, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2018, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2019, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2020, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2021, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2022, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2023, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2024, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2025, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2026, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2027, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2028, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2029, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2030, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2031, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2032, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2033, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2034, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2035, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2036, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2037, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2038, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2039, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2040, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2041, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2042, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2043, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2044, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2045, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2046, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2047, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2048, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2049, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2050, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2051, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2052, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2053, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2054, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2055, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2056, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2057, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2058, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2059, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2060, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2061, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2062, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2063, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2064, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2065, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2066, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2067, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2068, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2069, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2070, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2071, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2072, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2073, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2074, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2075, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2076, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2077, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2078, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2079, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2080, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2081, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2082, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2083, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2084, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2085, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2086, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2087, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2088, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2089, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2090, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2091, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2092, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2093, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2094, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2095, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2096, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2097, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2098, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2099, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2100, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2101, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2102, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2103, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2104, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2105, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2106, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2107, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2108, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2109, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2110, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2111, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2112, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2113, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2114, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2115, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2116, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2117, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2118, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2119, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2120, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2121, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2122, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2123, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2124, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2125, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2126, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2127, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2128, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2129, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2130, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2131, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2132, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2133, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2134, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2135, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2136, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2137, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2138, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (2139, 1, 'Power Crystal Ungoro', 0, 0);
INSERT INTO `pool_template` VALUES (10004, 1, 'Lady Anacondra : Wailing Cavern', 0, 0);
INSERT INTO `pool_template` VALUES (1320, 11, 'Sungrass in Eastern Plaguelands 35 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1321, 4, 'Stranglekelp in Azshara 12 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1322, 16, 'Stranglekelp in Darkshore 95 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1323, 3, 'Stranglekelp in Durotar 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1324, 5, 'Purple Lotus in Feralas 15 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1325, 4, 'Liferoot in Ashenvale 10 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1326, 2, 'Kingsblood in Swamp of Sorrows 6 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1327, 3, 'Gromsblood in Ashenvale 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1328, 3, 'Fadeleaf in Dustwallow Marsh 7 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1329, 7, 'Mithril Deposit in Azshara 22 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1330, 6, 'Mithril Deposit in Winterspring 19 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (12904, 1, 'Hyjal Black Lotus', 0, 0);
INSERT INTO `pool_template` VALUES (1332, 3, 'Gold Vein in Swamp of sorrows 9 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (1333, 2, 'Gold Vein in Burning Steppes 8 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (3011, 4, 'Scarlet Footlocker (EPL - Tyr)', 0, 0);
INSERT INTO `pool_template` VALUES (3012, 1, 'Pamela\'s Doll\'s Head', 0, 0);
INSERT INTO `pool_template` VALUES (3013, 1, 'Pamela\'s Doll\'s Left Side', 0, 0);
INSERT INTO `pool_template` VALUES (3014, 1, 'Pamela\'s Doll\'s Right Side', 0, 0);
INSERT INTO `pool_template` VALUES (3103, 1, 'AQ War Pax-lish', 0, 0);
INSERT INTO `pool_template` VALUES (3110, 1, 'AQ War Nokhor', 0, 0);
INSERT INTO `pool_template` VALUES (3111, 1, 'AQ War Nokhor', 0, 0);
INSERT INTO `pool_template` VALUES (2452, 1, 'Skhowl : 3 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (2453, 1, 'Lo\'Grosh : 2 spots possibles (Youfie).', 0, 0);
INSERT INTO `pool_template` VALUES (2598, 1, 'Darbel Montrose : 4 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (2605, 1, 'Zalas Witherbark - 4 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (2606, 1, 'Nimar the Slayer - 5 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (2779, 1, 'Prince Nazjak : 8 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (2783, 1, 'Marez Cowl : 2 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (14222, 1, 'Araga : 3 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (14223, 1, 'Cranky Benj : 4 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (14281, 1, 'Jimmy the Bleeder : 2 spots possibles (Youfie)', 0, 0);
INSERT INTO `pool_template` VALUES (42904, 5, 'scarab coffers spawn in AQ20', 0, 0);
INSERT INTO `pool_template` VALUES (3200, 1, 'Thuros Lightfingers', 0, 0);
INSERT INTO `pool_template` VALUES (3601, 1, 'Miner Johnson (3586) Deadmines', 0, 0);
INSERT INTO `pool_template` VALUES (12902, 1, 'Spawn Boss Blackfathom Deeps : Lorgus Jett', 0, 0);
INSERT INTO `pool_template` VALUES (1500, 1, 'Deadmines Ship Chest Random Spawn', 0, 0);
INSERT INTO `pool_template` VALUES (4701, 1, 'Blind Hunter (4425) Razorfen Kraul', 0, 0);
INSERT INTO `pool_template` VALUES (4702, 1, 'Earthcaller Halmgar (4842) Razorfen Kraul', 0, 0);
INSERT INTO `pool_template` VALUES (34901, 1, 'Meshlok the Harvester (12237) Maraudon', 0, 0);
INSERT INTO `pool_template` VALUES (9001, 1, 'Dark Iron Ambassador (6228) Gnomeregan', 0, 0);
INSERT INTO `pool_template` VALUES (9002, 1, 'Kernobee (7850) Gnomeregan', 0, 0);
INSERT INTO `pool_template` VALUES (12901, 1, 'Ragglesnout (7354) Razorfen Downs', 0, 0);
INSERT INTO `pool_template` VALUES (3301, 1, 'Fel Steed / Shadow Charger ShadowfangKeep', 0, 0);
INSERT INTO `pool_template` VALUES (3302, 1, 'Fel Steed / Shadow Charger ShadowfangKeep', 0, 0);
INSERT INTO `pool_template` VALUES (3303, 1, 'Fel Steed / Shadow Charger ShadowfangKeep', 0, 0);
INSERT INTO `pool_template` VALUES (7529302, 2, 'Wailing Cavern Chest Random Spawn', 0, 0);
INSERT INTO `pool_template` VALUES (7529501, 3, 'The Stockade Chest Random Spawn', 0, 0);
INSERT INTO `pool_template` VALUES (18901, 1, 'Graveyard Random Rare Boss spawn 1', 0, 0);
INSERT INTO `pool_template` VALUES (18902, 1, 'Graveyard Random Rare Boss spawn 2', 0, 0);
INSERT INTO `pool_template` VALUES (18907, 1, 'Graveyard Random Rare Boss spawn 7', 0, 0);
INSERT INTO `pool_template` VALUES (18906, 1, 'Graveyard Random Rare Boss spawn 6', 0, 0);
INSERT INTO `pool_template` VALUES (18905, 1, 'Graveyard Random Rare Boss spawn 5', 0, 0);
INSERT INTO `pool_template` VALUES (18904, 1, 'Graveyard Random Rare Boss spawn 4', 0, 0);
INSERT INTO `pool_template` VALUES (18903, 1, 'Graveyard Random Rare Boss spawn 3', 0, 0);
INSERT INTO `pool_template` VALUES (9003, 1, 'Test pool', 0, 0);
INSERT INTO `pool_template` VALUES (1319, 2, 'Rich Thorium Veins in Eastern Plaguelands Tyr Hand 5 objects total', 0, 0);
INSERT INTO `pool_template` VALUES (4291, 2, 'Dire Maul East - Dreamfoil', 0, 0);
INSERT INTO `pool_template` VALUES (34902, 4, 'Ghost Mushroom Maraudon', 0, 0);
INSERT INTO `pool_template` VALUES (1334, 50, 'Alterac Valley Mining Nodes', 0, 0);
INSERT INTO `pool_template` VALUES (1335, 1, 'Alterac Valley Black Lotus', 0, 0);
INSERT INTO `pool_template` VALUES (37000, 10, 'Silithus [Ooze Covered Rich Thorium Vein]', 0, 0);
INSERT INTO `pool_template` VALUES (2850, 1, 'rare Broken Tooth - 3 possible locations', 0, 0);
INSERT INTO `pool_template` VALUES (521, 1, 'rare Lupos - 3 possible locations', 0, 0);
INSERT INTO `pool_template` VALUES (14006, 13, 'Minion of Omen', 0, 11);
INSERT INTO `pool_template` VALUES (104, 2, 'Grave Moss (x7) - Stromgarde', 0, 0);
INSERT INTO `pool_template` VALUES (105, 5, 'Grave Moss (x27) - Raven Hill', 0, 0);
INSERT INTO `pool_template` VALUES (106, 2, 'Grave Moss (x6) - Tranquil Gardens', 0, 0);
INSERT INTO `pool_template` VALUES (107, 3, 'Grave Moss (x13) - Kodo Graveyard', 0, 0);
INSERT INTO `pool_template` VALUES (4292, 2, 'Dire Maul East - Gromsblood', 0, 0);
INSERT INTO `pool_template` VALUES (4293, 3, 'Dire Maul East - Ghost Mushroom', 0, 0);
INSERT INTO `pool_template` VALUES (1601, 1, 'Deathsworn Captain Spawn Pool - Shadowfang Keep', 0, 0);
INSERT INTO `pool_template` VALUES (1336, 1, 'Cortello\'s Riddle', 0, 0);
INSERT INTO `pool_template` VALUES (1337, 5, 'Burning Steppes Dark Iron', 0, 0);
INSERT INTO `pool_template` VALUES (1338, 4, 'Searing Gorge Dark Iron', 0, 0);
INSERT INTO `pool_template` VALUES (25468, 1, 'Stratholme - Hearthsinger Forresten', 0, 0);
INSERT INTO `pool_template` VALUES (1501, 1, 'Zul\'Farrak : Zerillis', 0, 0);
INSERT INTO `pool_template` VALUES (4294, 1, 'Dire Maul North - First Pack Pool of Pools', 0, 0);
INSERT INTO `pool_template` VALUES (4295, 4, 'Dire Maul North - First Pack Variant 1', 0, 0);
INSERT INTO `pool_template` VALUES (4296, 4, 'Dire Maul North - First Pack Variant 2', 0, 0);
INSERT INTO `pool_template` VALUES (4297, 3, 'Dire Maul North - First Pack Variant 3', 0, 0);
INSERT INTO `pool_template` VALUES (4298, 4, 'Dire Maul North - First Pack Variant 4', 0, 0);
INSERT INTO `pool_template` VALUES (4299, 3, 'Dire Maul North - First Pack Variant 5', 0, 0);
INSERT INTO `pool_template` VALUES (4300, 3, 'Dire Maul North - First Pack Variant 6', 0, 0);
INSERT INTO `pool_template` VALUES (25610, 4, 'BRD - Shadowforge Flame Keeper', 0, 0);
INSERT INTO `pool_template` VALUES (25609, 10, 'MC - Dark Iron Deposit', 0, 0);
INSERT INTO `pool_template` VALUES (22909, 1, 'LBRS - Inconspicuous Documents', 0, 0);
INSERT INTO `pool_template` VALUES (32979, 1, 'Strat - Rockwing Gargoyle / Rockwing Screecher / Stonespine', 0, 0);
INSERT INTO `pool_template` VALUES (25622, 6, 'BRD - Dark Iron Deposit', 0, 0);
INSERT INTO `pool_template` VALUES (462, 1, 'Vultros (462)', 0, 0);
INSERT INTO `pool_template` VALUES (21400, 8, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21401, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21402, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21403, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21404, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21405, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21406, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21407, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (21408, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #8', 0, 0);
INSERT INTO `pool_template` VALUES (21409, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #9', 0, 0);
INSERT INTO `pool_template` VALUES (21410, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #10', 0, 0);
INSERT INTO `pool_template` VALUES (21411, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #11', 0, 0);
INSERT INTO `pool_template` VALUES (21412, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #12', 0, 0);
INSERT INTO `pool_template` VALUES (21413, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #13', 0, 0);
INSERT INTO `pool_template` VALUES (21414, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #14', 0, 0);
INSERT INTO `pool_template` VALUES (21415, 1, 'Dun Morogh - Food Crate (3719) / Water Barrel (3658) - #15', 0, 0);
INSERT INTO `pool_template` VALUES (21450, 14, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21451, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21452, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21453, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21454, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21455, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21456, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21457, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (21458, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #8', 0, 0);
INSERT INTO `pool_template` VALUES (21459, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #9', 0, 0);
INSERT INTO `pool_template` VALUES (21460, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #10', 0, 0);
INSERT INTO `pool_template` VALUES (21461, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #11', 0, 0);
INSERT INTO `pool_template` VALUES (21462, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #12', 0, 0);
INSERT INTO `pool_template` VALUES (21463, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #13', 0, 0);
INSERT INTO `pool_template` VALUES (21464, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #14', 0, 0);
INSERT INTO `pool_template` VALUES (21465, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #15', 0, 0);
INSERT INTO `pool_template` VALUES (21466, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #16', 0, 0);
INSERT INTO `pool_template` VALUES (21467, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #17', 0, 0);
INSERT INTO `pool_template` VALUES (21468, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #18', 0, 0);
INSERT INTO `pool_template` VALUES (21469, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #19', 0, 0);
INSERT INTO `pool_template` VALUES (21470, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #20', 0, 0);
INSERT INTO `pool_template` VALUES (21471, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #21', 0, 0);
INSERT INTO `pool_template` VALUES (21472, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #22', 0, 0);
INSERT INTO `pool_template` VALUES (21473, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #23', 0, 0);
INSERT INTO `pool_template` VALUES (21474, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #24', 0, 0);
INSERT INTO `pool_template` VALUES (21475, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #25', 0, 0);
INSERT INTO `pool_template` VALUES (21476, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #26', 0, 0);
INSERT INTO `pool_template` VALUES (21477, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #27', 0, 0);
INSERT INTO `pool_template` VALUES (21478, 1, 'Elwynn Forest - Food Crate (3719) / Water Barrel (3658) - #28', 0, 0);
INSERT INTO `pool_template` VALUES (21500, 6, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21501, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21502, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21503, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21504, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21505, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21506, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21507, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (21508, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #8', 0, 0);
INSERT INTO `pool_template` VALUES (21509, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #9', 0, 0);
INSERT INTO `pool_template` VALUES (21510, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #10', 0, 0);
INSERT INTO `pool_template` VALUES (21511, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #11', 0, 0);
INSERT INTO `pool_template` VALUES (21512, 1, 'Teldrassil - Food Crate (3719) / Water Barrel (3658) - #12', 0, 0);
INSERT INTO `pool_template` VALUES (21550, 10, 'Durotar - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21551, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21552, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21553, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21554, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21555, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21556, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21557, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (21558, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #8', 0, 0);
INSERT INTO `pool_template` VALUES (21559, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #9', 0, 0);
INSERT INTO `pool_template` VALUES (21560, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #10', 0, 0);
INSERT INTO `pool_template` VALUES (21561, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #11', 0, 0);
INSERT INTO `pool_template` VALUES (21562, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #12', 0, 0);
INSERT INTO `pool_template` VALUES (21563, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #13', 0, 0);
INSERT INTO `pool_template` VALUES (21564, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #14', 0, 0);
INSERT INTO `pool_template` VALUES (21565, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #15', 0, 0);
INSERT INTO `pool_template` VALUES (21566, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #16', 0, 0);
INSERT INTO `pool_template` VALUES (21567, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #17', 0, 0);
INSERT INTO `pool_template` VALUES (21568, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #18', 0, 0);
INSERT INTO `pool_template` VALUES (21569, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #19', 0, 0);
INSERT INTO `pool_template` VALUES (21570, 1, 'Durotar - Food Crate (3719) / Water Barrel (3658) - #20', 0, 0);
INSERT INTO `pool_template` VALUES (21600, 8, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21601, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21602, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21603, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21604, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21605, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21606, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21607, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (21608, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #8', 0, 0);
INSERT INTO `pool_template` VALUES (21609, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #9', 0, 0);
INSERT INTO `pool_template` VALUES (21610, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #10', 0, 0);
INSERT INTO `pool_template` VALUES (21611, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #11', 0, 0);
INSERT INTO `pool_template` VALUES (21612, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #12', 0, 0);
INSERT INTO `pool_template` VALUES (21613, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #13', 0, 0);
INSERT INTO `pool_template` VALUES (21614, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #14', 0, 0);
INSERT INTO `pool_template` VALUES (21615, 1, 'Mulgore - Food Crate (3719) / Water Barrel (3658) - #15', 0, 0);
INSERT INTO `pool_template` VALUES (21650, 4, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - Master Pool', 0, 0);
INSERT INTO `pool_template` VALUES (21651, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (21652, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (21653, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (21654, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #4', 0, 0);
INSERT INTO `pool_template` VALUES (21655, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #5', 0, 0);
INSERT INTO `pool_template` VALUES (21656, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #6', 0, 0);
INSERT INTO `pool_template` VALUES (21657, 1, 'Tirisfal Glades - Food Crate (3719) / Water Barrel (3658) - #7', 0, 0);
INSERT INTO `pool_template` VALUES (42910, 1, 'BRD: Large Chest', 0, 0);
INSERT INTO `pool_template` VALUES (39801, 1, 'Western Plaguelands (Hearthglen) - Large Solid Chest (153463) / Large Mithril Bound Chest (153468) - #1', 0, 0);
INSERT INTO `pool_template` VALUES (39802, 1, 'Western Plaguelands (Hearthglen) - Large Solid Chest (153463) / Large Mithril Bound Chest (153468) - #2', 0, 0);
INSERT INTO `pool_template` VALUES (39803, 1, 'Western Plaguelands (Hearthglen) - Large Solid Chest (153463) / Large Mithril Bound Chest (153468) - #3', 0, 0);
INSERT INTO `pool_template` VALUES (39934, 1, 'Western Plaguelands (51-58) - Master Chest Pool', 0, 0);
INSERT INTO `pool_template` VALUES (3735, 1, 'Apothecary Falthis (3735)', 0, 0);
INSERT INTO `pool_template` VALUES (4301, 2, 'Dire Maul - Rich Thorium Vein', 0, 0);
INSERT INTO `pool_template` VALUES (1084, 1, 'Wild Steelbloom in Badlands', 0, 0);
INSERT INTO `pool_template` VALUES (1209, 1, 'Wild Steelbloom in Hillsbrad Foothills', 0, 0);
INSERT INTO `pool_template` VALUES (1223, 1, 'Sungrass in Silithus', 0, 0);
INSERT INTO `pool_template` VALUES (999, 1, 'Stranglekelp in Alterac Mountains', 0, 0);
INSERT INTO `pool_template` VALUES (1000, 1, 'Stranglekelp in The Hinterlands', 0, 0);
INSERT INTO `pool_template` VALUES (998, 1, 'Liferoot in Hillsbrad Foothills', 0, 0);
INSERT INTO `pool_template` VALUES (1055, 1, 'Khadgars Whisker in Azshara', 0, 0);
INSERT INTO `pool_template` VALUES (1054, 1, 'Herbs in Scarlet Monastery', 0, 0);
INSERT INTO `pool_template` VALUES (1052, 1, 'Bruiseweed in Arathi Highlands', 0, 0);
INSERT INTO `pool_template` VALUES (1053, 1, 'Herbs in Wailing Caverns', 0, 0);
INSERT INTO `pool_template` VALUES (42939, 1, 'Dustwallow Marsh: Drogoth the Roamer / Drogoth the Roamer', 0, 0);
INSERT INTO `pool_template` VALUES (43517, 1, 'Dustwallow Marsh: Burgle Eye / Burgle Eye', 0, 0);
INSERT INTO `pool_template` VALUES (43157, 1, 'Dustwallow Marsh: Ripscale / Ripscale', 0, 0);
INSERT INTO `pool_template` VALUES (43525, 1, 'Mossheart and Rotmaw', 0, 0);
INSERT INTO `pool_template` VALUES (43519, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (43524, 1, 'Dustwallow Marsh: Mithril Deposit', 0, 0);
INSERT INTO `pool_template` VALUES (43523, 1, 'Fish Node', 0, 0);
INSERT INTO `pool_template` VALUES (43522, 1, 'Dustwallow Marsh: Stranglekelp', 0, 0);
INSERT INTO `pool_template` VALUES (43521, 1, 'Dustwallow Marsh: Tin Vein', 0, 0);
INSERT INTO `pool_template` VALUES (43520, 4, 'Dustwallow Marsh: Iron Vein', 0, 0);
INSERT INTO `pool_template` VALUES (43518, 1, 'Undercity: Food Crate / Barrel of Milk', 0, 0);
INSERT INTO `pool_template` VALUES (4302, 1, 'Dire Maul - Large Mithril Bound Chest', 0, 0);
INSERT INTO `pool_template` VALUES (2200, 8, 'Chests in Dun Morogh', 0, 0);
INSERT INTO `pool_template` VALUES (2201, 3, 'Chests in Badlands', 0, 0);
INSERT INTO `pool_template` VALUES (2202, 1, 'Chests in Blasted Lands', 0, 0);
INSERT INTO `pool_template` VALUES (2203, 6, 'Chests in Swamp of Sorrows', 0, 0);
INSERT INTO `pool_template` VALUES (2204, 10, 'Chests in Duskwood', 0, 0);
INSERT INTO `pool_template` VALUES (2205, 12, 'Chests in Wetlands', 0, 0);
INSERT INTO `pool_template` VALUES (2206, 11, 'Chests in Elwynn Forest', 0, 0);
INSERT INTO `pool_template` VALUES (2207, 11, 'Chests in Durotar', 0, 0);
INSERT INTO `pool_template` VALUES (2208, 6, 'Chests in Dustwallow Marsh', 0, 0);
INSERT INTO `pool_template` VALUES (2209, 7, 'Chests in Azshara', 0, 0);
INSERT INTO `pool_template` VALUES (2210, 14, 'Chests in The Barrens', 0, 0);
INSERT INTO `pool_template` VALUES (2211, 3, 'Chests in Western Plaguelands', 0, 0);
INSERT INTO `pool_template` VALUES (2212, 13, 'Chests in Stranglethorn Vale', 0, 0);
INSERT INTO `pool_template` VALUES (2213, 10, 'Chests in Alterac Mountains', 0, 0);
INSERT INTO `pool_template` VALUES (2214, 9, 'Chests in Loch Modan', 0, 0);
INSERT INTO `pool_template` VALUES (2215, 9, 'Chests in Westfall', 0, 0);
INSERT INTO `pool_template` VALUES (2216, 10, 'Chests in Redridge Mountains', 0, 0);
INSERT INTO `pool_template` VALUES (2217, 11, 'Chests in Arathi Highlands', 0, 0);
INSERT INTO `pool_template` VALUES (2218, 5, 'Chests in Burning Steppes', 0, 0);
INSERT INTO `pool_template` VALUES (2219, 7, 'Chests in The Hinterlands', 0, 0);
INSERT INTO `pool_template` VALUES (2220, 3, 'Chests in Searing Gorge', 0, 0);
INSERT INTO `pool_template` VALUES (2221, 5, 'Chests in Tirisfal Glades', 0, 0);
INSERT INTO `pool_template` VALUES (2222, 11, 'Chests in Silverpine Forest', 0, 0);
INSERT INTO `pool_template` VALUES (2223, 6, 'Chests in Eastern Plaguelands', 0, 0);
INSERT INTO `pool_template` VALUES (2224, 7, 'Chests in Teldrassil', 0, 0);
INSERT INTO `pool_template` VALUES (2225, 8, 'Chests in Darkshore', 0, 0);
INSERT INTO `pool_template` VALUES (2226, 7, 'Chests in Mulgore', 0, 0);
INSERT INTO `pool_template` VALUES (2227, 8, 'Chests in Hillsbrad Foothills', 0, 0);
INSERT INTO `pool_template` VALUES (2228, 8, 'Chests in Ashenvale', 0, 0);
INSERT INTO `pool_template` VALUES (2229, 4, 'Chests in Thousand Needles', 0, 0);
INSERT INTO `pool_template` VALUES (2230, 6, 'Chests in Desolace', 0, 0);
INSERT INTO `pool_template` VALUES (2231, 6, 'Chests in Stonetalon Mountains', 0, 0);
INSERT INTO `pool_template` VALUES (2232, 6, 'Chests in Tanaris', 0, 0);
INSERT INTO `pool_template` VALUES (2233, 3, 'Chests in Winterspring', 0, 0);
INSERT INTO `pool_template` VALUES (2234, 1, 'Chests in The Deadmines', 0, 0);
INSERT INTO `pool_template` VALUES (42906, 2, 'Patch of Elemental Water Eastern Kingdoms', 0, 0);


SET FOREIGN_KEY_CHECKS = 1;
