/*
 Navicat MySQL Data Transfer

 Source Server         : _localhost
 Source Server Type    : MariaDB
 Source Server Version : 100428 (10.4.28-MariaDB)
 Source Host           : localhost:3306
 Source Schema         : tw_world

 Target Server Type    : MariaDB
 Target Server Version : 100428 (10.4.28-MariaDB)
 File Encoding         : 65001

 Date: 11/01/2024 13:18:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for taxi_path_transitions
-- ----------------------------
DROP TABLE IF EXISTS `taxi_path_transitions`;
CREATE TABLE `taxi_path_transitions`  (
  `in_path` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `out_path` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `in_node` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `out_node` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `comment` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`in_path`, `out_path`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of taxi_path_transitions
-- ----------------------------
INSERT INTO `taxi_path_transitions` VALUES (499, 482, 20, 1, 'Everlook, Winterspring -> Valormok, Azshara -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (500, 363, 17, 2, 'Valormok, Azshara -> Everlook, Winterspring -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (499, 291, 20, 3, 'Everlook, Winterspring -> Valormok, Azshara -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (499, 284, 20, 3, 'Everlook, Winterspring -> Valormok, Azshara -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (487, 450, 24, 2, 'Freewind Post, Thousand Needles -> Camp Mojache, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (487, 375, 24, 2, 'Freewind Post, Thousand Needles -> Camp Mojache, Feralas -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (486, 422, 27, 1, 'Camp Mojache, Feralas -> Freewind Post, Thousand Needles -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (485, 320, 11, 4, 'Revantusk Village, The Hinterlands -> Hammerfall, Arathi -> Kargath, Badlands');
INSERT INTO `taxi_path_transitions` VALUES (484, 473, 19, 2, 'Hammerfall, Arathi -> Revantusk Village, The Hinterlands -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (482, 351, 22, 3, 'Valormok, Azshara -> Splintertree Post, Ashenvale -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (481, 500, 26, 2, 'Splintertree Post, Ashenvale -> Valormok, Azshara -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (481, 400, 27, 2, 'Splintertree Post, Ashenvale -> Valormok, Azshara -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (478, 373, 20, 6, 'Stonetalon Peak, Stonetalon Mountains -> Nijel\'s Point, Desolace -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (478, 141, 20, 7, 'Stonetalon Peak, Stonetalon Mountains -> Nijel\'s Point, Desolace -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (477, 444, 25, 2, 'Nijel\'s Point, Desolace -> Stonetalon Peak, Stonetalon Mountains -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (476, 276, 8, 7, 'Chillwind Camp, Western Plaguelands -> Aerie Peak, The Hinterlands -> Refuge Pointe, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (474, 485, 14, 1, 'Light\'s Hope Chapel, Eastern Plaguelands -> Revantusk Village, The Hinterlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (474, 412, 14, 2, 'Light\'s Hope Chapel, Eastern Plaguelands -> Revantusk Village, The Hinterlands -> Tarren Mill, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (471, 457, 22, 3, 'Feathermoon, Feralas -> Cenarion Hold, Silithus -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (470, 257, 13, 4, 'Morgan\'s Vigil, Burning Steppes -> Lakeshire, Redridge -> Darkshire, Duskwood');
INSERT INTO `taxi_path_transitions` VALUES (469, 410, 9, 4, 'Lakeshire, Redridge -> Morgan\'s Vigil, Burning Steppes -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (470, 254, 13, 4, 'Morgan\'s Vigil, Burning Steppes -> Lakeshire, Redridge -> Sentinel Hill, Westfall');
INSERT INTO `taxi_path_transitions` VALUES (467, 465, 32, 1, 'Astranaar, Ashenvale -> Talrendis Point, Azshara -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (468, 443, 32, 1, 'Talrendis Point, Azshara -> Astranaar, Ashenvale -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (467, 447, 32, 1, 'Astranaar, Ashenvale -> Talrendis Point, Azshara -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (467, 446, 32, 1, 'Astranaar, Ashenvale -> Talrendis Point, Azshara -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (466, 468, 14, 1, 'Ratchet, The Barrens -> Talrendis Point, Azshara -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (466, 332, 14, 2, 'Ratchet, The Barrens -> Talrendis Point, Azshara -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (466, 447, 14, 2, 'Ratchet, The Barrens -> Talrendis Point, Azshara -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (466, 329, 14, 1, 'Ratchet, The Barrens -> Talrendis Point, Azshara -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (461, 417, 12, 2, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (461, 360, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (461, 355, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (461, 334, 12, 2, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (461, 354, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (461, 287, 12, 2, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (461, 283, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (461, 281, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (461, 45, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (461, 279, 12, 2, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (461, 44, 12, 1, 'Ratchet, The Barrens -> Crossroads, The Barrens -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (460, 222, 11, 2, 'Ratchet, The Barrens -> Theramore, Dustwallow Marsh -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (460, 163, 11, 1, 'Ratchet, The Barrens -> Theramore, Dustwallow Marsh -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (460, 56, 11, 2, 'Ratchet, The Barrens -> Theramore, Dustwallow Marsh -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (330, 446, 52, 2, 'Auberdine, Darkshore -> Talrendis Point, Azshara -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (445, 329, 21, 1, 'Theramore, Dustwallow Marsh -> Talrendis Point, Azshara -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (455, 451, 14, 4, 'Marshal\'s Refuge, Un\'Goro Crater -> Cenarion Hold, Silithus -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (454, 449, 14, 5, 'Marshal\'s Refuge, Un\'Goro Crater -> Cenarion Hold, Silithus -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (453, 388, 13, 5, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (453, 311, 15, 2, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (452, 323, 14, 3, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (453, 223, 13, 4, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (452, 201, 14, 3, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (451, 374, 27, 1, 'Cenarion Hold, Silithus -> Feathermoon, Feralas -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (451, 326, 27, 1, 'Cenarion Hold, Silithus -> Feathermoon, Feralas -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (451, 225, 27, 1, 'Cenarion Hold, Silithus -> Feathermoon, Feralas -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (450, 456, 25, 2, 'Camp Mojache, Feralas -> Cenarion Hold, Silithus -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (449, 486, 27, 2, 'Cenarion Hold, Silithus -> Camp Mojache, Feralas -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (449, 375, 21, 10, 'Cenarion Hold, Silithus -> Camp Mojache, Feralas -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (449, 353, 27, 3, 'Cenarion Hold, Silithus -> Camp Mojache, Feralas -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (449, 227, 27, 3, 'Cenarion Hold, Silithus -> Camp Mojache, Feralas -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (448, 468, 17, 1, 'Everlook, Winterspring -> Talrendis Point, Azshara -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (448, 465, 17, 2, 'Everlook, Winterspring -> Talrendis Point, Azshara -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (448, 446, 17, 2, 'Everlook, Winterspring -> Talrendis Point, Azshara -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (181, 222, 113, 3, 'Auberdine, Darkshore -> Theramore, Dustwallow Marsh -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (447, 298, 19, 3, 'Talrendis Point, Azshara -> Everlook, Winterspring -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (201, 182, 18, 3, 'Gadgetzan, Tanaris -> Theramore, Dustwallow Marsh -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (446, 56, 19, 2, 'Talrendis Point, Azshara -> Theramore, Dustwallow Marsh -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (444, 467, 21, 1, 'Stonetalon Peak, Stonetalon Mountains -> Astranaar, Ashenvale -> Talrendis Point, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (443, 478, 23, 2, 'Astranaar, Ashenvale -> Stonetalon Peak, Stonetalon Mountains -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (440, 413, 12, 2, 'The Sepulcher, Silverpine Forest -> Tarren Mill, Hillsbrad -> Revantusk Village, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (440, 322, 12, 3, 'The Sepulcher, Silverpine Forest -> Tarren Mill, Hillsbrad -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (437, 404, 35, 9, 'Light\'s Hope Chapel, Eastern Plaguelands -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (432, 346, 12, 4, 'Light\'s Hope Chapel, Eastern Plaguelands -> Chillwind Camp, Western Plaguelands -> Southshore, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (437, 12, 35, 16, 'Light\'s Hope Chapel, Eastern Plaguelands -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (429, 404, 24, 9, 'Chillwind Camp, Western Plaguelands -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (429, 12, 24, 16, 'Chillwind Camp, Western Plaguelands -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (427, 410, 23, 4, 'Stormwind, Elwynn -> Morgan\'s Vigil, Burning Steppes -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (424, 201, 21, 3, 'Cenarion Hold, Silithus -> Gadgetzan, Tanaris -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (421, 487, 19, 2, 'Camp Taurajo, The Barrens -> Freewind Post, Thousand Needles -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (421, 308, 19, 2, 'Camp Taurajo, The Barrens -> Freewind Post, Thousand Needles -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (420, 162, 12, 2, 'Camp Taurajo, The Barrens -> Thunder Bluff, Mulgore -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (416, 462, 10, 1, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (416, 360, 10, 1, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (416, 354, 10, 1, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (416, 334, 10, 2, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (416, 287, 10, 1, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (416, 283, 10, 2, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (416, 45, 10, 1, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (416, 279, 10, 2, 'Camp Taurajo, The Barrens -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (412, 441, 16, 2, 'Revantusk Village, The Hinterlands -> Tarren Mill, Hillsbrad -> The Sepulcher, Silverpine Forest');
INSERT INTO `taxi_path_transitions` VALUES (413, 473, 13, 5, 'Tarren Mill, Hillsbrad -> Revantusk Village, The Hinterlands -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (411, 470, 9, 7, 'Thorium Point, Searing Gorge -> Morgan\'s Vigil, Burning Steppes -> Lakeshire, Redridge');
INSERT INTO `taxi_path_transitions` VALUES (411, 425, 9, 5, 'Thorium Point, Searing Gorge -> Morgan\'s Vigil, Burning Steppes -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (410, 402, 10, 5, 'Morgan\'s Vigil, Burning Steppes -> Thorium Point, Searing Gorge -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (411, 381, 9, 6, 'Thorium Point, Searing Gorge -> Morgan\'s Vigil, Burning Steppes -> Nethergarde Keep, Blasted Lands');
INSERT INTO `taxi_path_transitions` VALUES (407, 362, 11, 2, 'Thorium Point, Searing Gorge -> Kargath, Badlands -> Grom\'gol, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (407, 319, 7, 3, 'Thorium Point, Searing Gorge -> Kargath, Badlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (407, 38, 7, 5, 'Thorium Point, Searing Gorge -> Kargath, Badlands -> Undercity, Tirisfal');
INSERT INTO `taxi_path_transitions` VALUES (407, 37, 11, 2, 'Thorium Point, Searing Gorge -> Kargath, Badlands -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (404, 411, 17, 3, 'Ironforge, Dun Morogh -> Thorium Point, Searing Gorge -> Morgan\'s Vigil, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (402, 438, 12, 11, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (402, 428, 12, 14, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Chillwind Camp, Western Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (402, 263, 12, 18, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Aerie Peak, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (402, 18, 12, 15, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Menethil Harbor, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (402, 16, 12, 16, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (401, 482, 45, 1, 'Bloodvenom Post, Felwood -> Valormok, Azshara -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (398, 335, 47, 3, 'Everlook, Winterspring -> Orgrimmar, Durotar -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (398, 224, 47, 3, 'Everlook, Winterspring -> Orgrimmar, Durotar -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (390, 459, 13, 2, 'Brackenwall Village, Dustwallow Marsh -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (390, 310, 13, 2, 'Brackenwall Village, Dustwallow Marsh -> Gadgetzan, Tanaris -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (387, 328, 10, 9, 'Thunder Bluff, Mulgore -> Orgrimmar, Durotar -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (384, 386, 28, 7, 'Nijel\'s Point, Desolace -> Auberdine, Darkshore -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (384, 289, 32, 3, 'Nijel\'s Point, Desolace -> Auberdine, Darkshore -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (384, 101, 32, 3, 'Nijel\'s Point, Desolace -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (382, 410, 19, 4, 'Nethergarde Keep, Blasted Lands -> Morgan\'s Vigil, Burning Steppes -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (380, 408, 36, 3, 'Stonard, Swamp of Sorrows -> Flame Crest, Burning Steppes -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (379, 343, 35, 3, 'Flame Crest, Burning Steppes -> Stonard, Swamp of Sorrows -> Grom\'gol, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (379, 121, 35, 4, 'Flame Crest, Burning Steppes -> Stonard, Swamp of Sorrows -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (377, 319, 16, 3, 'Flame Crest, Burning Steppes -> Kargath, Badlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (377, 38, 16, 5, 'Flame Crest, Burning Steppes -> Kargath, Badlands -> Undercity, Tirisfal');
INSERT INTO `taxi_path_transitions` VALUES (376, 486, 32, 2, 'Shadowprey Village, Desolace -> Camp Mojache, Feralas -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (376, 450, 23, 12, 'Shadowprey Village, Desolace -> Camp Mojache, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (376, 391, 32, 1, 'Shadowprey Village, Desolace -> Camp Mojache, Feralas -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (374, 477, 30, 2, 'Feathermoon, Feralas -> Nijel\'s Point, Desolace -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (375, 356, 30, 8, 'Camp Mojache, Feralas -> Shadowprey Village, Desolace -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (373, 471, 29, 2, 'Nijel\'s Point, Desolace -> Feathermoon, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (373, 326, 30, 1, 'Nijel\'s Point, Desolace -> Feathermoon, Feralas -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (372, 465, 50, 2, 'Talonbranch Glade, Felwood -> Talrendis Point, Azshara -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (372, 446, 50, 2, 'Talonbranch Glade, Felwood -> Talrendis Point, Azshara -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (369, 385, 34, 5, 'Talonbranch Glade, Felwood -> Auberdine, Darkshore -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (369, 226, 34, 4, 'Talonbranch Glade, Felwood -> Auberdine, Darkshore -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (369, 101, 37, 3, 'Talonbranch Glade, Felwood -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (369, 51, 37, 1, 'Talonbranch Glade, Felwood -> Auberdine, Darkshore -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (369, 59, 37, 1, 'Talonbranch Glade, Felwood -> Auberdine, Darkshore -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (368, 385, 18, 1, 'Moonglade -> Auberdine, Darkshore -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (368, 226, 18, 1, 'Moonglade -> Auberdine, Darkshore -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (368, 101, 18, 2, 'Moonglade -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (368, 59, 18, 1, 'Moonglade -> Auberdine, Darkshore -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (368, 51, 18, 1, 'Moonglade -> Auberdine, Darkshore -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (366, 499, 23, 1, 'Moonglade -> Everlook, Winterspring -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (367, 448, 20, 5, 'Moonglade -> Everlook, Winterspring -> Talrendis Point, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (364, 286, 32, 8, 'Moonglade -> Bloodvenom Post, Felwood -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (361, 406, 68, 2, 'Grom\'gol, Stranglethorn -> Kargath, Badlands -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (361, 319, 64, 3, 'Grom\'gol, Stranglethorn -> Kargath, Badlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (361, 38, 64, 5, 'Grom\'gol, Stranglethorn -> Kargath, Badlands -> Undercity, Tirisfal');
INSERT INTO `taxi_path_transitions` VALUES (359, 20, 20, 25, 'Light\'s Hope Chapel, Eastern Plaguelands -> Undercity, Tirisfal -> The Sepulcher, Silverpine Forest');
INSERT INTO `taxi_path_transitions` VALUES (358, 376, 27, 2, 'Sun Rock Retreat, Stonetalon Mountains -> Shadowprey Village, Desolace -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (355, 450, 34, 2, 'Crossroads, The Barrens -> Camp Mojache, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (356, 280, 38, 2, 'Shadowprey Village, Desolace -> Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (353, 462, 41, 1, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (353, 360, 38, 4, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (353, 354, 41, 1, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (353, 287, 41, 1, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (353, 334, 41, 2, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (353, 283, 41, 2, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (353, 45, 41, 2, 'Camp Mojache, Feralas -> Crossroads, The Barrens -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (352, 276, 23, 4, 'Light\'s Hope Chapel, Eastern Plaguelands -> Aerie Peak, The Hinterlands -> Refuge Pointe, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (350, 481, 46, 4, 'Zoram\'gar Outpost, Ashenvale -> Splintertree Post, Ashenvale -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (350, 327, 46, 3, 'Zoram\'gar Outpost, Ashenvale -> Splintertree Post, Ashenvale -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (348, 162, 26, 2, 'Brackenwall Village, Dustwallow Marsh -> Thunder Bluff, Mulgore -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (346, 272, 23, 3, 'Chillwind Camp, Western Plaguelands -> Southshore, Hillsbrad -> Menethil Harbor, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (344, 380, 48, 3, 'Grom\'gol, Stranglethorn -> Stonard, Swamp of Sorrows -> Flame Crest, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (333, 462, 31, 1, 'Splintertree Post, Ashenvale -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (333, 417, 31, 2, 'Splintertree Post, Ashenvale -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (333, 355, 31, 1, 'Splintertree Post, Ashenvale -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (333, 281, 31, 1, 'Splintertree Post, Ashenvale -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (333, 279, 31, 2, 'Splintertree Post, Ashenvale -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (329, 101, 51, 3, 'Talrendis Point, Azshara -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (328, 351, 19, 3, 'Orgrimmar, Durotar -> Splintertree Post, Ashenvale -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (327, 335, 13, 10, 'Splintertree Post, Ashenvale -> Orgrimmar, Durotar -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (327, 42, 13, 10, 'Splintertree Post, Ashenvale -> Orgrimmar, Durotar -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (327, 224, 19, 4, 'Splintertree Post, Ashenvale -> Orgrimmar, Durotar -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (326, 324, 26, 3, 'Feathermoon, Feralas -> Thalanaar, Feralas -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (326, 57, 26, 2, 'Feathermoon, Feralas -> Thalanaar, Feralas -> Theramore, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (325, 374, 28, 1, 'Thalanaar, Feralas -> Feathermoon, Feralas -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (325, 471, 26, 2, 'Thalanaar, Feralas -> Feathermoon, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (325, 225, 28, 2, 'Thalanaar, Feralas -> Feathermoon, Feralas -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (324, 458, 29, 1, 'Thalanaar, Feralas -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (323, 325, 31, 1, 'Gadgetzan, Tanaris -> Thalanaar, Feralas -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (322, 320, 18, 3, 'Tarren Mill, Hillsbrad -> Hammerfall, Arathi -> Kargath, Badlands');
INSERT INTO `taxi_path_transitions` VALUES (321, 441, 18, 2, 'Hammerfall, Arathi -> Tarren Mill, Hillsbrad -> The Sepulcher, Silverpine Forest');
INSERT INTO `taxi_path_transitions` VALUES (320, 378, 39, 2, 'Hammerfall, Arathi -> Kargath, Badlands -> Flame Crest, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (320, 406, 39, 2, 'Hammerfall, Arathi -> Kargath, Badlands -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (320, 362, 39, 2, 'Hammerfall, Arathi -> Kargath, Badlands -> Grom\'gol, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (320, 317, 39, 2, 'Hammerfall, Arathi -> Kargath, Badlands -> Stonard, Swamp of Sorrows');
INSERT INTO `taxi_path_transitions` VALUES (320, 37, 39, 2, 'Hammerfall, Arathi -> Kargath, Badlands -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (319, 321, 37, 3, 'Kargath, Badlands -> Hammerfall, Arathi -> Tarren Mill, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (319, 484, 37, 2, 'Kargath, Badlands -> Hammerfall, Arathi -> Revantusk Village, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (318, 38, 44, 6, 'Stonard, Swamp of Sorrows -> Kargath, Badlands -> Undercity, Tirisfal');
INSERT INTO `taxi_path_transitions` VALUES (318, 319, 45, 4, 'Stonard, Swamp of Sorrows -> Kargath, Badlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (310, 422, 16, 2, 'Gadgetzan, Tanaris -> Freewind Post, Thousand Needles -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (309, 459, 48, 3, 'Thunder Bluff, Mulgore -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (308, 459, 18, 3, 'Freewind Post, Thousand Needles -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (308, 388, 19, 2, 'Freewind Post, Thousand Needles -> Gadgetzan, Tanaris -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (305, 462, 57, 1, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (305, 417, 57, 2, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (305, 360, 57, 1, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (305, 355, 57, 1, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (305, 287, 55, 4, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (305, 281, 57, 1, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (305, 279, 57, 2, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (305, 44, 57, 1, 'Zoram\'gar Outpost, Ashenvale -> Crossroads, The Barrens -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (304, 462, 26, 1, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (304, 417, 26, 2, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (304, 354, 26, 1, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (304, 334, 26, 2, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (304, 283, 26, 1, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (304, 287, 26, 1, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (304, 279, 26, 2, 'Brackenwall Village, Dustwallow Marsh -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (298, 368, 21, 2, 'Everlook, Winterspring -> Moonglade -> Auberdine, Darkshore');
INSERT INTO `taxi_path_transitions` VALUES (291, 162, 28, 2, 'Valormok, Azshara -> Thunder Bluff, Mulgore -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (290, 500, 32, 2, 'Thunder Bluff, Mulgore -> Valormok, Azshara -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (289, 367, 18, 7, 'Auberdine, Darkshore -> Moonglade -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (287, 365, 42, 10, 'Crossroads, The Barrens -> Bloodvenom Post, Felwood -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (286, 462, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (286, 417, 48, 2, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (286, 360, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (286, 355, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (286, 354, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (286, 279, 48, 2, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (286, 281, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (286, 44, 48, 1, 'Bloodvenom Post, Felwood -> Crossroads, The Barrens -> Thunder Bluff, Mulgore');
INSERT INTO `taxi_path_transitions` VALUES (284, 417, 23, 2, 'Valormok, Azshara -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (284, 462, 23, 1, 'Valormok, Azshara -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (284, 355, 23, 1, 'Valormok, Azshara -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (284, 281, 23, 1, 'Valormok, Azshara -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (284, 279, 22, 6, 'Valormok, Azshara -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (283, 500, 21, 2, 'Crossroads, The Barrens -> Valormok, Azshara -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (282, 462, 20, 1, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (282, 354, 20, 1, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (282, 334, 20, 2, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (282, 287, 20, 1, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (282, 283, 20, 2, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (282, 279, 20, 2, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (282, 45, 20, 1, 'Freewind Post, Thousand Needles -> Crossroads, The Barrens -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (280, 462, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (280, 417, 27, 2, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (280, 360, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (280, 334, 27, 2, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Splintertree Post, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (280, 354, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (280, 283, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (280, 287, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (280, 45, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (280, 281, 27, 1, 'Sun Rock Retreat, Stonetalon Mountains -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (276, 268, 12, 3, 'Aerie Peak, The Hinterlands -> Refuge Pointe, Arathi -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (275, 475, 11, 7, 'Refuge Pointe, Arathi -> Aerie Peak, The Hinterlands -> Chillwind Camp, Western Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (275, 349, 14, 3, 'Refuge Pointe, Arathi -> Aerie Peak, The Hinterlands -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (274, 268, 11, 3, 'Southshore, Hillsbrad -> Refuge Pointe, Arathi -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (271, 347, 10, 2, 'Menethil Harbor, Wetlands -> Southshore, Hillsbrad -> Chillwind Camp, Western Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (271, 230, 10, 3, 'Menethil Harbor, Wetlands -> Southshore, Hillsbrad -> Aerie Peak, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (267, 275, 27, 3, 'Thelsamar, Loch Modan -> Refuge Pointe, Arathi -> Aerie Peak, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (267, 273, 27, 3, 'Thelsamar, Loch Modan -> Refuge Pointe, Arathi -> Southshore, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (264, 404, 30, 9, 'Aerie Peak, The Hinterlands -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (264, 12, 30, 16, 'Aerie Peak, The Hinterlands -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (262, 252, 15, 4, 'Nethergarde Keep, Blasted Lands -> Darkshire, Duskwood -> Sentinel Hill, Westfall');
INSERT INTO `taxi_path_transitions` VALUES (262, 258, 17, 3, 'Nethergarde Keep, Blasted Lands -> Darkshire, Duskwood -> Lakeshire, Redridge');
INSERT INTO `taxi_path_transitions` VALUES (262, 259, 17, 3, 'Nethergarde Keep, Blasted Lands -> Darkshire, Duskwood -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (260, 261, 22, 4, 'Booty Bay, Stranglethorn -> Darkshire, Duskwood -> Nethergarde Keep, Blasted Lands');
INSERT INTO `taxi_path_transitions` VALUES (260, 258, 22, 4, 'Booty Bay, Stranglethorn -> Darkshire, Duskwood -> Lakeshire, Redridge');
INSERT INTO `taxi_path_transitions` VALUES (258, 469, 14, 1, 'Darkshire, Duskwood -> Lakeshire, Redridge -> Morgan\'s Vigil, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (257, 261, 14, 5, 'Lakeshire, Redridge -> Darkshire, Duskwood -> Nethergarde Keep, Blasted Lands');
INSERT INTO `taxi_path_transitions` VALUES (257, 259, 15, 4, 'Lakeshire, Redridge -> Darkshire, Duskwood -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (250, 261, 15, 6, 'Sentinel Hill, Westfall -> Darkshire, Duskwood -> Nethergarde Keep, Blasted Lands');
INSERT INTO `taxi_path_transitions` VALUES (249, 469, 30, 1, 'Sentinel Hill, Westfall -> Lakeshire, Redridge -> Morgan\'s Vigil, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (244, 13, 43, 5, 'Nethergarde Keep, Blasted Lands -> Stormwind, Elwynn -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (242, 335, 31, 3, 'Valormok, Azshara -> Orgrimmar, Durotar -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (242, 224, 31, 3, 'Valormok, Azshara -> Orgrimmar, Durotar -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (230, 349, 20, 3, 'Southshore, Hillsbrad -> Aerie Peak, The Hinterlands -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (229, 272, 11, 2, 'Aerie Peak, The Hinterlands -> Southshore, Hillsbrad -> Menethil Harbor, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (228, 450, 43, 2, 'Thunder Bluff, Mulgore -> Camp Mojache, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (226, 471, 65, 2, 'Auberdine, Darkshore -> Feathermoon, Feralas -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (225, 386, 73, 6, 'Feathermoon, Feralas -> Auberdine, Darkshore -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (226, 326, 65, 1, 'Auberdine, Darkshore -> Feathermoon, Feralas -> Thalanaar, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (225, 289, 78, 3, 'Feathermoon, Feralas -> Auberdine, Darkshore -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (225, 101, 78, 3, 'Feathermoon, Feralas -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (224, 459, 89, 3, 'Orgrimmar, Durotar -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (222, 458, 22, 1, 'Theramore, Dustwallow Marsh -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (222, 394, 22, 2, 'Theramore, Dustwallow Marsh -> Gadgetzan, Tanaris -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (201, 464, 17, 3, 'Gadgetzan, Tanaris -> Theramore, Dustwallow Marsh -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (201, 163, 18, 4, 'Gadgetzan, Tanaris -> Theramore, Dustwallow Marsh -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (163, 477, 55, 2, 'Theramore, Dustwallow Marsh -> Nijel\'s Point, Desolace -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (161, 419, 38, 2, 'Shadowprey Village, Desolace -> Thunder Bluff, Mulgore -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (161, 387, 38, 1, 'Shadowprey Village, Desolace -> Thunder Bluff, Mulgore -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (161, 345, 38, 2, 'Shadowprey Village, Desolace -> Thunder Bluff, Mulgore -> Brackenwall Village, Dustwallow Marsh');
INSERT INTO `taxi_path_transitions` VALUES (161, 290, 38, 2, 'Shadowprey Village, Desolace -> Thunder Bluff, Mulgore -> Valormok, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (141, 464, 66, 1, 'Nijel\'s Point, Desolace -> Theramore, Dustwallow Marsh -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (141, 222, 66, 2, 'Nijel\'s Point, Desolace -> Theramore, Dustwallow Marsh -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (102, 386, 8, 3, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (102, 385, 8, 3, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Nijel\'s Point, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (102, 226, 8, 3, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (102, 289, 12, 2, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (102, 59, 8, 3, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Stonetalon Peak, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (82, 380, 86, 2, 'Booty Bay, Stranglethorn -> Stonard, Swamp of Sorrows -> Flame Crest, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (102, 51, 8, 3, 'Rut\'theran Village, Teldrassil -> Auberdine, Darkshore -> Astranaar, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (58, 386, 19, 6, 'Stonetalon Peak, Stonetalon Mountains -> Auberdine, Darkshore -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (58, 289, 21, 3, 'Stonetalon Peak, Stonetalon Mountains -> Auberdine, Darkshore -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (57, 464, 25, 1, 'Thalanaar, Feralas -> Theramore, Dustwallow Marsh -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (58, 101, 21, 3, 'Stonetalon Peak, Stonetalon Mountains -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (56, 325, 25, 1, 'Theramore, Dustwallow Marsh -> Thalanaar, Feralas -> Feathermoon, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (50, 386, 24, 8, 'Astranaar, Ashenvale -> Auberdine, Darkshore -> Talonbranch Glade, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (50, 289, 32, 3, 'Astranaar, Ashenvale -> Auberdine, Darkshore -> Moonglade');
INSERT INTO `taxi_path_transitions` VALUES (50, 101, 33, 3, 'Astranaar, Ashenvale -> Auberdine, Darkshore -> Rut\'theran Village, Teldrassil');
INSERT INTO `taxi_path_transitions` VALUES (47, 462, 25, 1, 'Orgrimmar, Durotar -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (47, 417, 25, 2, 'Orgrimmar, Durotar -> Crossroads, The Barrens -> Camp Taurajo, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (47, 355, 25, 1, 'Orgrimmar, Durotar -> Crossroads, The Barrens -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (47, 281, 25, 1, 'Orgrimmar, Durotar -> Crossroads, The Barrens -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (47, 279, 25, 2, 'Orgrimmar, Durotar -> Crossroads, The Barrens -> Sun Rock Retreat, Stonetalon Mountains');
INSERT INTO `taxi_path_transitions` VALUES (46, 462, 24, 2, 'Thunder Bluff, Mulgore -> Crossroads, The Barrens -> Ratchet, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (46, 354, 24, 2, 'Thunder Bluff, Mulgore -> Crossroads, The Barrens -> Zoram\'gar Outpost, Ashenvale');
INSERT INTO `taxi_path_transitions` VALUES (46, 287, 24, 2, 'Thunder Bluff, Mulgore -> Crossroads, The Barrens -> Bloodvenom Post, Felwood');
INSERT INTO `taxi_path_transitions` VALUES (44, 162, 30, 2, 'Crossroads, The Barrens -> Thunder Bluff, Mulgore -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (42, 162, 42, 2, 'Orgrimmar, Durotar -> Thunder Bluff, Mulgore -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (41, 13, 47, 7, 'Booty Bay, Stranglethorn -> Stormwind, Elwynn -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (39, 406, 143, 2, 'Undercity, Tirisfal -> Kargath, Badlands -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (39, 378, 143, 2, 'Undercity, Tirisfal -> Kargath, Badlands -> Flame Crest, Burning Steppes');
INSERT INTO `taxi_path_transitions` VALUES (39, 362, 143, 2, 'Undercity, Tirisfal -> Kargath, Badlands -> Grom\'gol, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (39, 317, 143, 2, 'Undercity, Tirisfal -> Kargath, Badlands -> Stonard, Swamp of Sorrows');
INSERT INTO `taxi_path_transitions` VALUES (39, 37, 143, 2, 'Undercity, Tirisfal -> Kargath, Badlands -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (36, 406, 39, 2, 'Booty Bay, Stranglethorn -> Kargath, Badlands -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (36, 319, 35, 3, 'Booty Bay, Stranglethorn -> Kargath, Badlands -> Hammerfall, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (36, 38, 35, 5, 'Booty Bay, Stranglethorn -> Kargath, Badlands -> Undercity, Tirisfal');
INSERT INTO `taxi_path_transitions` VALUES (26, 404, 27, 9, 'Southshore, Hillsbrad -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (26, 12, 27, 16, 'Southshore, Hillsbrad -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (21, 357, 22, 20, 'The Sepulcher, Silverpine Forest -> Undercity, Tirisfal -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (17, 404, 19, 9, 'Menethil Harbor, Wetlands -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (17, 12, 19, 16, 'Menethil Harbor, Wetlands -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (15, 404, 22, 9, 'Thelsamar, Loch Modan -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (15, 12, 22, 16, 'Thelsamar, Loch Modan -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (13, 438, 45, 11, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Light\'s Hope Chapel, Eastern Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (13, 428, 45, 15, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Chillwind Camp, Western Plaguelands');
INSERT INTO `taxi_path_transitions` VALUES (13, 263, 45, 18, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Aerie Peak, The Hinterlands');
INSERT INTO `taxi_path_transitions` VALUES (13, 18, 45, 16, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Menethil Harbor, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (13, 16, 45, 15, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (12, 40, 65, 5, 'Ironforge, Dun Morogh -> Stormwind, Elwynn -> Booty Bay, Stranglethorn');
INSERT INTO `taxi_path_transitions` VALUES (12, 6, 65, 5, 'Ironforge, Dun Morogh -> Stormwind, Elwynn -> Sentinel Hill, Westfall');
INSERT INTO `taxi_path_transitions` VALUES (7, 13, 24, 5, 'Sentinel Hill, Westfall -> Stormwind, Elwynn -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (272, 17, 11, 6, 'Southshore, Hillsbrad -> Menethil Harbor, Wetlands -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (18, 271, 34, 3, 'Ironforge, Dun Morogh -> Menethil Harbor, Wetlands -> Southshore, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (35, 361, 19, 7, 'Booty Bay, Stranglethorn -> Grom\'gol, Stranglethorn -> Kargath, Badlands');
INSERT INTO `taxi_path_transitions` VALUES (18, 269, 34, 4, 'Ironforge, Dun Morogh -> Menethil Harbor, Wetlands -> Refuge Pointe, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (270, 17, 18, 3, 'Refuge Pointe, Arathi -> Menethil Harbor, Wetlands -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (45, 399, 12, 6, 'Crossroads, The Barrens -> Orgrimmar, Durotar -> Everlook, Winterspring');
INSERT INTO `taxi_path_transitions` VALUES (398, 47, 38, 9, 'Everlook, Winterspring -> Orgrimmar, Durotar -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (499, 242, 19, 5, 'Everlook, Winterspring -> Valormok, Azshara -> Orgrimmar, Durotar');
INSERT INTO `taxi_path_transitions` VALUES (453, 389, 15, 1, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Camp Mojache, Feralas');
INSERT INTO `taxi_path_transitions` VALUES (389, 375, 35, 2, 'Gadgetzan, Tanaris -> Camp Mojache, Feralas -> Shadowprey Village, Desolace');
INSERT INTO `taxi_path_transitions` VALUES (391, 459, 24, 3, 'Camp Mojache, Feralas -> Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater');
INSERT INTO `taxi_path_transitions` VALUES (456, 453, 14, 4, 'Cenarion Hold, Silithus -> Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (459, 454, 12, 3, 'Gadgetzan, Tanaris -> Marshal\'s Refuge, Un\'Goro Crater -> Cenarion Hold, Silithus');
INSERT INTO `taxi_path_transitions` VALUES (281, 308, 21, 2, 'Crossroads, The Barrens -> Freewind Post, Thousand Needles -> Gadgetzan, Tanaris');
INSERT INTO `taxi_path_transitions` VALUES (310, 282, 16, 2, 'Gadgetzan, Tanaris -> Freewind Post, Thousand Needles -> Crossroads, The Barrens');
INSERT INTO `taxi_path_transitions` VALUES (464, 466, 10, 2, 'Theramore, Dustwallow Marsh -> Ratchet, The Barrens -> Talrendis Point, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (51, 467, 29, 2, 'Auberdine, Darkshore -> Astranaar, Ashenvale -> Talrendis Point, Azshara');
INSERT INTO `taxi_path_transitions` VALUES (453, 310, 14, 3, 'Marshal\'s Refuge, Un\'Goro Crater -> Gadgetzan, Tanaris -> Freewind Post, Thousand Needles');
INSERT INTO `taxi_path_transitions` VALUES (265, 93, 25, 3, 'Thelsamar, Loch Modan -> Menethil Harbor, Wetlands -> Dun Agrath, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (95, 91, 26, 1, 'Ironforge, Dun Morogh -> Ironforge Airfields, Dun Morogh -> Dun Agrath, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (94, 16, 7, 18, 'Ironforge Airfields, Dun Morogh -> Ironforge, Dun Morogh -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (94, 12, 11, 17, 'Ironforge Airfields, Dun Morogh -> Ironforge, Dun Morogh -> Stormwind, Elwynn');
INSERT INTO `taxi_path_transitions` VALUES (94, 404, 11, 9, 'Ironforge Airfields, Dun Morogh -> Ironforge, Dun Morogh -> Thorium Point, Searing Gorge');
INSERT INTO `taxi_path_transitions` VALUES (93, 90, 3, 2, 'Menethil Harbor, Wetlands -> Dun Agrath, Wetlands -> Ironforge Airfields, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (92, 266, 1, 6, 'Dun Agrath, Wetlands -> Menethil Harbor, Wetlands -> Thelsamar, Loch Modan');
INSERT INTO `taxi_path_transitions` VALUES (92, 269, 1, 6, 'Dun Agrath, Wetlands -> Menethil Harbor, Wetlands -> Refuge Point, Arathi');
INSERT INTO `taxi_path_transitions` VALUES (92, 271, 1, 4, 'Dun Agrath, Wetlands -> Menethil Harbor, Wetlands -> Southshore, Hillsbrad');
INSERT INTO `taxi_path_transitions` VALUES (91, 92, 6, 1, 'Ironforge Airfields, Dun Morogh -> Dun Agrath, Wetlands -> Menethil Harbor, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (90, 94, 5, 1, 'Dun Agrath, Wetlands -> Ironforge Airfields, Dun Morogh -> Ironforge, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (18, 93, 30, 4, 'Ironforge, Dun Morogh -> Menethil Harbor, Wetlands -> Dun Agrath, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (15, 95, 18, 19, 'Thelsamar, Loch Modan -> Ironforge, Dun Morogh -> Ironforge Airfields, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (13, 95, 46, 15, 'Stormwind, Elwynn -> Ironforge, Dun Morogh -> Ironforge Airfields, Dun Morogh');
INSERT INTO `taxi_path_transitions` VALUES (270, 93, 18, 1, 'Refuge Pointe, Arathi -> Menethil Harbor, Wetlands -> Dun Agrath, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (272, 93, 11, 1, 'Southshore, Hillsbrad -> Menethil Harbor, Wetlands -> Dun Agrath, Wetlands');
INSERT INTO `taxi_path_transitions` VALUES (402, 95, 13, 14, 'Thorium Point, Searing Gorge -> Ironforge, Dun Morogh -> Ironforge Airfields, Dun Morogh');


SET FOREIGN_KEY_CHECKS = 1;
